server:
  port: 8888

spring:
  cache:
    type: ehcache
    ehcache:
      config: ehcache.xml
  redis:
    database: 0
    host: 172.16.255.231
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 1
    timeout: 5000